---
title: 'BIDA405: Lesson Plan, Week 1'
author: "Martin Monkman"
date: 'latest revision: `r Sys.Date()`'
output:
  word_document: default
  html_document: default
description: Data Analytics Provisioning, Importing, Extracting and Manipulation,
  UVic BIDA405
---




## Readings & Reference Materials

### Installing R and RStudio

Garrett Grolemund, _Hands-On Programming with R_

* [Appendix A: "Installing R and RStudio"](https://rstudio-education.github.io/hopr/starting.html)

* [Appendix B: "R Packages"](https://rstudio-education.github.io/hopr/packages2.html)


J.D. Long and Paul Teetor, _R Cookbook (2nd edition)_

* ["Getting Started and Getting Help"](https://rc2e.com/gettingstarted)

* See recipes 1.1 through 1.3


## Reading list


Sharon E. Ellis and Jeffrey T. Leek, "How to Share Data for Collaboration", _The American Statistician_, 72:1, 553-57, 2018

* [UVic library link](https://www-tandfonline-com.ezproxy.library.uvic.ca/doi/pdf/10.1080/00031305.2017.1375987?needAccess=true)




Paul Murrell, _Introduction to Data Technologies_:

* Chapter 5, "Data Storage"

  - pages 63–143

  - [online version](https://www.stat.auckland.ac.nz/~paul/ItDT/HTML/node36.html)


* [entire book: homepage](https://www.stat.auckland.ac.nz/~paul/ItDT/)

* [UVic library link](https://learning-oreilly-com.ezproxy.library.uvic.ca/library/view/introduction-to-data/9781420065183/?ar?orpq&email=oJbr4Ho8VLXz0zbFzjLK2g%3d%3d&tstamp=1595819339&id=081854077E8F5A7C7006AE8AEE9FEC6EE37CC34A)


Benjamin S. Baumer, "A Grammar for Reproducible and Painless Extract-Transform-Load Operations on Medium Data", 2017

* [link](https://arxiv.org/abs/1708.07073)


Jay Gendron, _Introduction to R for Business Intelligence_, Packt Publishing, 2016

* [UVic library link](https://learning-oreilly-com.ezproxy.library.uvic.ca/library/view/~/9781785280252/?ar%3Forpq=&email=oJbr4Ho8VLXz0zbFzjLK2g%3D%3D&tstamp=1628136907&id=EE63DB77881D1BF27AA83B63A471A4BB79F5367B)




-30-
