---
title: "BIDA405: Lesson Plan, Week 4"
subtitle: "2020-09-26 & 2020-09-27"
author: "Martin Monkman"
date: "latest revision: `r Sys.Date()`"
output:
  word_document: default
  html_document: default
description: "Data Analytics Provisioning, Importing, Extracting and Manipulation, UVic BIDA405"
---




## Readings & Reference Materials



## Reading list

### Tidy data

Hadley Wickham, Wickham, Hadley. 2014. “Tidy Data.” _Journal of Statistical Software_ 59 (1): 1–23. https://doi.org/10.18637/jss.v059.i10.

* a concise summary of tidy data principles can be found in [_R for Data Science_, "Tidy Data"](https://r4ds.had.co.nz/tidy-data.html)



### Strings


Samuel E. Buttrey and Lyn R. Whitaker, _A Data Scientist's Guide to Acquiring, Cleaning and Managing Data in R_ (2017):

* Chapter 4, "R Data, Part 3: Text and Factors"

* [UVic Library link](https://learning-oreilly-com.ezproxy.library.uvic.ca/library/view/a-data-scientists/9781119080022/c07.xhtml#c7)


### Data manipulation


Nina Zumel and John Mount, _Practical Data Science with R (2nd edition)_ (2020)

* Chapter 4 "Managing Data" (4.2 Data transformations)

* Chapter 5, "Data engineering and data shaping"

* [UVic library link](https://learning-oreilly-com.ezproxy.library.uvic.ca/library/view/practical-data-science/9781617295874/?ar?orpq&email=oJbr4Ho8VLXz0zbFzjLK2g%3d%3d&tstamp=1600527352&id=DC7689B4AD2FA446468DD1CE0CCCD91B187CD9C4)



Mark van der Loo and Edwin de Jonge, _Statistical Data Cleaning with Applications in R_ (2018):

* Chapter 11, "Example: A Small Data-Cleaning System"

* [UVic Library link](https://learning-oreilly-com.ezproxy.library.uvic.ca/library/view/statistical-data-cleaning/9781118897157/c11.xhtml#c11)


### SQL

Thomas Nield, _Getting Started with SQL: A Hands-On Approach for Beginners_ (2016)

* Chapter 2, "Databases"

* Chapter 9, "Database design"

* Installing SQLite: Chapter 3, "SQLite"

* [UVic Library link](https://proquestcombo-safaribooksonline-com.ezproxy.library.uvic.ca/9781491938607?ar&orpq&email=oJbr4Ho8VLXz0zbFzjLK2g%3d%3d&tstamp=1600913295&id=2C359E41B596290424E03BF0F243BBA36BFDDBFA)


### R packages




-30-
