# Course Materials

## R References

Garrett Grolemund and Hadley Wickham, _R for Data Science_. 

* the book, in its most up-to-date form, is freely available online at [r4ds.had.co.nz](https://r4ds.had.co.nz/)

* paperback and ebook version are available at the UVic Bookstore or other retailers


## Data Wrangling and Cleaning

Joseph M. Hellerstein, Tye Rattenbury, Jeffrey Heer, Sean Kandel, Connor Carreras, _Principles of Data Wrangling_, O'Reilly, 2017

* [ebook through UVic library](https://learning-oreilly-com.ezproxy.library.uvic.ca/library/view/principles-of-data/9781491938911/?ar?orpq&email=oJbr4Ho8VLXz0zbFzjLK2g%3d%3d&tstamp=1593872116&id=264B1B6FB9757E417BF02832AB953DFB5A1A0BAC)



Samuel E. Buttrey and Lyn R. Whitaker, _A Data Scientist's Guide to Acquiring, Cleaning, and Managing Data in R_, Wiley, 2017

* [ebook through UVic library](https://learning-oreilly-com.ezproxy.library.uvic.ca/library/view/a-data-scientists/9781119080022/?ar?orpq&email=oJbr4Ho8VLXz0zbFzjLK2g%3d%3d&tstamp=1592592308&id=175D472B1E5E7B940BAC7864955E6D12F53E946C)


Mark van der Loo and Edwin de Jonge, _Statistical Data Cleaning with Applications in R_, Wiley, 2018

* [ebook through UVic library](https://learning-oreilly-com.ezproxy.library.uvic.ca/library/view/statistical-data-cleaning/9781118897157/?ar?orpq&email=oJbr4Ho8VLXz0zbFzjLK2g%3d%3d&tstamp=1592592591&id=68FE450A07DAFB7CA03C510C6B5244B071582E5C)


## SQL

Upom Malik, Matt Goldwasser, Benjamin Johnston, _The Applied SQL Data Analytics Workshop_, Second Edition, Packt Publishing, 2020

* [ebook through UVic library](https://learning-oreilly-com.ezproxy.library.uvic.ca/library/view/the-applied-sql/9781800203679/?ar?orpq&email=oJbr4Ho8VLXz0zbFzjLK2g%3d%3d&tstamp=1593790034&id=5C43481E85991A0D697A764F25E420A1AB57B3C5)

Thomas Nield, _Getting Started with SQL_, O'Reilly Media, 2016

* [ebook through UVic library](https://learning-oreilly-com.ezproxy.library.uvic.ca/library/view/getting-started-with/9781491938607/?ar?orpq&email=oJbr4Ho8VLXz0zbFzjLK2g%3d%3d&tstamp=1593796819&id=F83C6F48C5BC64763F30C2ED5D0DB2F4C5C1CEA5)


John L. Viescas, _SQL Queries for Mere Mortals: A Hands-On Guide to Data manipulation in SQL_ Fourth Edition, Addison-Wesley, 2018

* when you are ready to move on to more complicated queries

* [ebook through UVic library](https://learning-oreilly-com.ezproxy.library.uvic.ca/library/view/sql-queries-for/9780134858432/cover.xhtml)



## Additional Reading

Other resources&#8212;some required, some vital reference resources, and some optional "food for thought"&#8212;will be included in the  materials for each week's class. A cumulative resource list will be made available as part of this course site.

Steve Tale, _SQL: The Ultimate Beginners Guide: Learn SQL Today_, CreateSpace Independent Publishing Platform, 2016

* This book is available for purchase as kindle or paper, at a relatively low cost. It's another good introduction to SQL that you might want to investigate if you find yourself doing more SQL


### Other text books


Garrett Grolemund, [_Hands-On Programming with R_](https://rstudio-education.github.io/hopr/)

Chester Ismay and Albert Y. Kim, [An Introduction to Statistical and Data Sciences via R](http://moderndive.com/) _a.k.a._ "Modern Dive"

Roger Peng, 2019-12-22, [_R Programming for Data Science_](https://bookdown.org/rdpeng/rprogdatascience/)


### Articles

Karl Broman and Kara Woo, ["Data organization in spreadsheets"](https://doi.org/10.1080/00031305.2017.1375989), _The American Statistician_ 72 (1): 2–10.

[Data Organization in Spreadsheets for Social Scientists: Formatting problems](https://datacarpentry.org/spreadsheets-socialsci/02-common-mistakes/index.html) -- DataCarpentry lesson

Hilary Parker, 2017-08-31, [Opinionated Analysis Development](https://peerj.com/preprints/3210/)

Hadley Wickham. ["Tidy data"](https://vita.had.co.nz/papers/tidy-data.html), _The Journal of Statistical Software_, vol. 59, 2014.

Wilson G, Bryan J, Cranston K, Kitzes J, Nederbragt L, Teal TK (2017) "Good enough practices in scientific computing", PLoS Comput Biol 13(6): e1005510. [https://doi.org/10.1371/journal.pcbi.1005510](https://doi.org/10.1371/journal.pcbi.1005510)

***

## Data Sources

[FiveThirtyEight](https://fivethirtyeight-r.netlify.com/articles/fivethirtyeight.html)

[Gapminder](https://www.gapminder.org/data/)

[Tidy Tuesday](https://github.com/rfordatascience/tidytuesday)

***

## R resources

[RStudio projects](https://support.rstudio.com/hc/en-us/articles/200526207-Using-Projects)


-30-

