---
title: 'BIDA405: Course Outline'
author: "Martin Monkman"
date: "`r Sys.Date()`"
output:
  word_document: default
  html_document: default
---



# Data Analytics Provisioning, Importing, Extracting and Manipulation: BIDA405

Dates: 2020-09-05 to 2020-10-11
Time:  9:00 am–12:00 pm
Days: Saturday, Sunday



## Prerequisites

It is recommended that students have completed BIDA301 Business Intelligence and Data Analytics Fundamentals or have basic experience coding in R or Python as well as experience using formulas in Excel.



## Instructor

Martin Monkman

* email: <mmonkman@uvic.ca>

* skype: <a href="skype:monkmanmh?call">monkmanmh</a>


virtual (skype) office hours:

* Tuesday, 8:00 pm - 9:00 pm

* or by appointment (send me an email)



## Course content

RStudio cloud:

* This course uses rstudio.cloud

* To access the course site, please click this link: [rstudio.cloud: BIDA405_2020F]()

* You will need to create an account (if you don't have one already) when you initially log in


Moodle:

* This course uses Moodle—an online learning management system—as a supplementary resource for the class. 

* To access, login to [https://distance.moodle.uvcs.uvic.ca/](https://distance.moodle.uvcs.uvic.ca/) with your Netlink ID.


Text: 

* _think about this!_

* Additional readings will be introduced with each lesson.

***

## Continuing Studies Statement on Use of Educational Technology

This course will require the use of RStudio Cloud and may use other education technology such as internet-based applications, cloud services, or social media. In order to complete this course you will be required to either consent to the disclosure of your personal information outside of Canada to enable use of these technologies, or work with the instructor to use other privacy protective options (such as using an alias or nickname).

