---
title: "BIDA405: Lesson Plan, Week 1"
subtitle: "2020-09-05 & 2020-09-05 "
author: "Martin Monkman"
date: "latest revision: `r Sys.Date()`"
output: html_document
description: "Data Analytics Provisioning, Importing, Extracting and Manipulation, UVic BIDA405"
---





### 1a. Welcome!

Format: participation and instructor lecture w/ slides

Time allocation: 30 minutes (9:00 to 9:30)


#### Welcome!

* Course content: summary

* Introducing the instructor

* Value of community 

  - Icebreaker [breakout rooms?]
  


#### What to expect in this class

* read the syllabus!

* course flow

* readings

* assignments and evaluation





### 1c-i. An introduction to Moodle and Zoom

Format: participation and instructor lecture w/ slides

Time allocation: 45 minutes (9:45 to 10:30)

### 1c-ii. An introduction to RStudio Cloud

Format: participation and instructor lecture w/ slides

Time allocation: 15 minutes (9:45 to 10:30)


## BREAK

Time allocation: 15 minutes (10:30 to 10:45)

***

### 2a. The Data Science Process

Format: instructor, lecture w/slides

Time allocation: 15 minutes (10:45 to 11:00)


### 2b. Data Import and Manipulation

Format: instructor, lecture w/slides

Time allocation: 15 minutes (10:45 to 11:00)



Format: learner (instructor guided)

Time allocation: 60 minutes (11:00 to 12:00)

***

## LUNCH

Time allocation: 60 minutes (12:00 to 1:00)

***

### 3a. The Data Science Process -- example walkthrough

Format: instructor, lecture w/slides

Time allocation: 30 minutes (1:00 to 1:30)


### 3b. Data Wrangling (part 2)

Format: instructor, lecture w/slides

Time allocation: 15 minutes (1:30 to 1:45)


Format: learner (instructor guided)

Time allocation: 60 minutes (1:45 to 2:45)


***

## BREAK

Time allocation: 15 minutes (2:45 to 3:00)


***

## 4a. Assignment #1

Time allocation: 30 minutes (3:00 to 3:30)


## 4b. Wrap up

Time allocation: 30 minutes (3:30 to 4:00)

### Summary

Format: instructor summary, w/ slides

### Questions?

Format: learner Q&A

### Preview/readings for next lesson

Format: instructor summary, w/ slides



***

