---
title: "BIDA405: Lesson Plan, Week 1"
subtitle: "2020-09-05 & 2020-09-06"
author: "Martin Monkman"
date: "latest revision: `r Sys.Date()`"
output:
  word_document: default
  html_document: default
description: "Data Analytics Provisioning, Importing, Extracting and Manipulation, UVic BIDA405"
---

# Unit learning plan

## Saturday

2020-09-05


### 1a. Welcome!

Format: participation and instructor lecture w/ slides

Time allocation: 30 minutes (9:00 to 9:30)


#### Welcome!

_Introduction to BIDA405: instructor, tools, and course structure_


* Course content: summary

* Introducing the instructor

* Read the syllabus!

What to expect in this class

* course flow

* readings

* assignments and evaluation





### 1c-i. An introduction to Moodle and Zoom

Format: participation and instructor lecture w/ slides

Time allocation: 45 minutes (9:45 to 10:30)

- Activity: breakout rooms—practice breakout rooms

- Introduce yourself to three others by answering the question "What's one thing you haven't been able to do because of the pandemic?"





## BREAK

Time allocation: 15 minutes (10:30 to 10:45)

***

## Introduction to the data science process

_Understand how provisioning, importing, extracting and manipulation fits into the whole of a data analytics project_


### 2a. The Data Science Process 

Format: instructor, lecture w/slides

Time allocation: 30 minutes (10:45 to 11:15)


### 2b. Introduction to R & RStudio 

_Demonstrate familiarity with the R programming language_


Format: instructor, lecture w/slides

Time allocation: 15 minutes (11:15 to 11:30)




### 2b. Tonight's reading and wrap-up 


Format: instructor, lecture w/slides

Time allocation: 15 minutes (11:30 to noon)


#### Reading: How data is stored

Please read Ellis and Leek, "How to Share Data for Collaboration" (link below). The article is aimed at scientists ("data generators") who are have collected the data and are preparing it for further analysis in an academic environment—the authors speak about "preparing data for a statistician". 

While Ellis and Leek have a specific context in mind, the principles in their paper have broad applicability, and the practices are be essential in any environment, including a business, government, or non-profit organization. And in those contexts, the roles and responsibilities are often different. The data collection and storage is often to support a business need, and the use of the data for business intelligence is a secondary benefit. As a result, there is often a middle person who isn't involved in the collection of the data, but who does the preparation of the data for the modeling, visualization, and reporting.

On Sunday morning, we will be going into breakout groups to discuss the following questions:

* What things do Ellis and Leek say you should pass to the person doing the modeling, visualization and reporting?

* What are the three things that should be in the data dictionary?

* Why would you want to prepare the items in the first two bullets by using a scripting environment (such as **R**) rather than a GUI (Graphical User Interface)?

  - Watch Hadley Wickham's presentation "You can't do data science in a GUI" (40 minutes) https://vimeo.com/240400798 
  
  - The slide deck is here: https://speakerdeck.com/hadley/you-cant-do-data-science-in-a-gui?slide=45


***

## Sunday

2020-09-06



### 3a. Discussion: How data is stored

_Discussion: responding to readings_

Format: instructor, lecture w/slides

Time allocation: 10 minutes (9:00 to 9:10)

Format: learner groups (instructor guided), breakout rooms

Time allocation: 10 minutes (9:10 to 9:20)

Format: learner group report out

Time allocation: 10 minutes (9:20 to 9:30)




### 3b. Data import: spreadsheets

_Importing a plain text flat file and an Excel file; dealing with anomalies_


Format: instructor, lecture w/slides

Time allocation: 15 minutes (9:30 to 9:45)


Format: learner (instructor guided)

Time allocation: 45 minutes (9:45 to 10:30)


***

## BREAK

Time allocation: 15 minutes (10:30 to 10:45)


***

### 4a. Data import: other file formats (SPSS, STATA, etc)

_Importing a flat file from a proprietary data tool_


Format: instructor, lecture w/slides

Time allocation: 15 minutes (10:45 to 11:00)


Format: learner (instructor guided)

Time allocation: 30 minutes (11:00 to 11:30)


## 4b. Assignment #1

_Introduction of Assignment #1_


Time allocation: 15 minutes (11:30 to 11:45)


## 4c. Wrap up

Time allocation: 15 minutes (11:45 to 12:00)

### Summary

Format: instructor summary, w/ slides

### Preview/readings for next lesson

Format: instructor summary, w/ slides

### Questions?

Format: learner Q&A




***

