---
title: "BIDA405: Lesson Plan, Week 2"
subtitle: "2020-09-12 & 2020-09-13 "
author: "Martin Monkman"
date: "latest revision: `r Sys.Date()`"
output:
  word_document: default
  html_document: default
description: "Data Analytics Provisioning, Importing, Extracting and Manipulation, UVic BIDA405"
---

# Unit learning plan

## Saturday

2020-09-12


### 1a. Homework review

Format: instructor lecture w/ slides

Time allocation: 15 minutes (9:00 to 9:15)


Format: breakout rooms

Time allocation: 15 minutes (9:15 to 9:30)



### 1b. Importing other data formats

_Import SPSS, database (db), and dataframe_


Format: instructor, lecture w/slides

Time allocation: 15 minutes (10:45 to 11:00)



Format: hands-on exercise, learner (instructor guided)

Time allocation: 60 minutes (11:00 to 12:00)

Activity:

* import various files




## BREAK

Time allocation: 15 minutes (10:30 to 10:45)

***


### 2a. Regular expressions

_Demonstrate basic understanding of regular expressions and their utility_

Format: instructor lecture w/ slides

Time allocation: 15 minutes (9:30 to 10:30)


Format: hands-on exercise

Time allocation: 45 minutes (9:45 to 10:30)


  - RStudio Cloud / regex101.com exercise
  

### 2b. Homework - Readings: webpage format

Format: instructor, lecture w/slides

Time allocation: 15 minutes (11:45 to 11:00)



***

## Sunday

2020-09-13


### 3a. Discussion - Readings: webpage format

Format: instructor lecture w/ slides

Time allocation: 15 minutes (9:00 to 9:15)


Format: breakout rooms

Time allocation: 15 minutes (9:15 to 9:30)


### 3b. Webscraping - introduction

_Discussion: responding to readings_

Format: instructor, lecture w/slides

Time allocation: 10 minutes (9:00 to 9:10)

Format: learner groups (instructor guided), breakout rooms

Time allocation: 10 minutes (9:10 to 9:20)

Format: learner group report out

Time allocation: 10 minutes (9:20 to 9:30)




***

## BREAK

Time allocation: 15 minutes (10:30 to 10:45)


***

### 4a. Webscraping - using regular expressions to find what you want

_Reading data from a webpage_


Format: instructor, lecture w/slides

Time allocation: 15 minutes (10:45 to 11:00)


Format: learner (instructor guided)

Time allocation: 30 minutes (11:00 to 11:30)


## 4b. Assignment #2

_Introduction of Assignment #2_


Time allocation: 15 minutes (11:30 to 11:45)


## 4c. Wrap up

Time allocation: 15 minutes (11:45 to 12:00)

### Summary

Format: instructor summary, w/ slides

### Preview/readings for next lesson

Format: instructor summary, w/ slides

### Questions?

Format: learner Q&A




***

