---
title: "BIDA405: Lesson Plan, Week 3"
subtitle: "2020-09-19 & 2020-09-20 "
author: "Martin Monkman"
date: "latest revision: `r Sys.Date()`"
output:
  word_document: default
  html_document: default
description: "Data Analytics Provisioning, Importing, Extracting and Manipulation, UVic BIDA405"
---


***

**_subject to change_**



## Objectives

> “Without a systematic way to start and keep data clean, bad data will happen.” — Donato Diorio


At the end of the first part of this lesson, learners will:

1. Be able to explain the attributes of "good data" (and by extension, be able to identify "bad data"); and 

1. Demonstrate an understanding of tools to validate data quality;   


At the end of the second part of this lesson, learners will:

1. Demonstrate an understanding of tools and techniques to programatically identify and correct problems with data.


***

## Activities: summary

| Block      | Time           | Topics  | &#8212; |
|---         |:---            |:---     |:---:  |
|**Saturday**|**Data quality**     |&#8212; |&#8212; |
|1a          | 9:00 to 9:30   | Homework review  | &#8212; |
|1b          | 9:30 to 10:30  | The nature of bad data <br> Hierarchy of data quality | &#8212; |
|&#8212:     | 10:30 to 10:45 | _break_ | &#8212; |
|2a          | 10:45 to 11:30 | Data validation methods | &#8212; |
|2b          | 11:30 to 12:00 | Homework <br> - Readings: data quality | &#8212; |
|**Sunday**  |**Data cleaning** |&#8212; |&#8212; |
|3a          | 9:00 to 9:30   | Discussion <br> - Readings: data quality  | &#8212; |
|3b          | 9:30 to 10:30  | Data cleaning - introduction | &#8212; |
|&#8212:     | 10:30 to 10:45 | _break_ | &#8212; |
|4a          | 10:45 to 11:45 | Data cleaning - tools and techniques | 
|4b          | 11:45 to 12:00 | Homework assignment <br> Wrap-up and summary | &#8212; |


***

