---
title: "BIDA405: Lesson Plan, Week 3"
subtitle: "2020-09-19 & 2020-09-20 "
author: "Martin Monkman"
date: "latest revision: `r Sys.Date()`"
output:
  word_document: default
  html_document: default
description: "Data Analytics Provisioning, Importing, Extracting and Manipulation, UVic BIDA405"
---

# Unit learning plan

## Saturday

2020-09-19


### 1a. Homework review

Format: instructor lecture w/ slides

Time allocation: 15 minutes (9:00 to 9:15)


Format: breakout rooms

Time allocation: 15 minutes (9:15 to 9:30)

Question to discuss: 

* What was one thing in the week 1 assignment or week 2 exercise that you might still wonder about?



### 1b. The nature of bad data 

_Data quality_


Format: instructor, lecture w/slides

Time allocation: 15 minutes (9:45 to 10:15)


Format: hands-on exercise, learner (instructor guided)

Time allocation: 60 minutes (11:00 to 12:00)

Activity:

* find problems in the data




## BREAK

Time allocation: 15 minutes (10:30 to 10:45)

***


### 2a. Data validation methods

_Demonstrate..._

Format: instructor lecture w/ slides

Time allocation: 15 minutes (10:45 to 11:00)


Format: hands-on exercise

Time allocation: 45 minutes (11:00 to 11:45)


  - R exercise
  

### 2b. Homework - Readings: Naming things

Format: instructor, lecture w/slides

Time allocation: 15 minutes (11:45 to 11:00)

I have learned the hard way that being organized and having a system for naming files pay benefits now and in the future. It can also help the people you collaborate with—they can find your files more easily, and they can easily locate the elements of your project that they need.

> Your closest collaborator is you six months ago, but you don't reply to emails.
— Karl Broman

_You_ will be the beneficiary of a more organized and systematic workflow. Even if you never come back to a project in the future, if you are organized and name things well now, it will help avoid the future with a dark timeline.



> File organization and naming are powerful weapons against chaos.
— Jenny Bryan

Please read Karl Broman, "Tools for Reproducible Research: Organizing projects; exploratory data analysis":
https://kbroman.org/Tools4RR/assets/lectures/06_org_eda_withnotes.pdf

* What are the three steps of the basic principles that Broman emphasizes?

> There are only two hard things in Computer Science: cache invalidation and naming things.
— Phil Karlton from Martin Fowler

Please read Jenny Bryan, "Naming Things", presentation to Reproducible Science Workshop: https://speakerdeck.com/jennybc/how-to-name-files

* What are the three principles for file names?  Be ready to explain in your own words what the three principles mean.


***

## Sunday

2020-09-20


### 3a. Discussion - Readings: Naming things

Format: instructor lecture w/ slides

Time allocation: 15 minutes (9:00 to 9:15)


Format: breakout rooms

Time allocation: 15 minutes (9:15 to 9:30)


### 3b. Data cleaning - introduction

_Discussion: responding to readings_

Format: instructor, lecture w/slides

Time allocation: 10 minutes (9:00 to 9:10)

Format: learner groups (instructor guided), breakout rooms

Time allocation: 10 minutes (9:10 to 9:20)

Format: learner group report out

Time allocation: 10 minutes (9:20 to 9:30)




***

## BREAK

Time allocation: 15 minutes (10:30 to 10:45)


***

### 4a. Data cleaning - tools and techniques


Format: instructor, lecture w/slides

Time allocation: 15 minutes (10:45 to 11:00)


Format: learner (instructor guided)

Time allocation: 30 minutes (11:00 to 11:30)


## 4b. Assignment #3

_Introduction of Assignment #3_


Time allocation: 15 minutes (11:30 to 11:45)


## 4c. Wrap up

Time allocation: 15 minutes (11:45 to 12:00)

### Summary

Format: instructor summary, w/ slides

### Preview/readings for next lesson

Format: instructor summary, w/ slides

### Questions?

Format: learner Q&A




***

