---
title: 'BIDA405: Curriculum Blueprint'
author: "Martin Monkman"
date: "`r Sys.Date()`"
output:
  word_document: default
  html_document: default
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Data Analytics Provisioning, Importing, Extracting and Manipulation: BIDA405



## Course description

This course will explore the fundamentals of coding and scripting for Data Analytics. You will develop the ability to script and code for basic tasks in Data Analytics in common data analytic tools such as SQL, R, Python, and Excel. This will allow you to import and export data appropriately and perform fundamental data manipulations and to automate basic analysis elements.

### Learning objectives

* Construct complex scripts in R, Python and SQL to solve problems.

* Apply appropriate safeguards for data privacy and security

Perform the following basic tasks in R, Python, and SQL as appropriate:

* Import and export data

* Clean data

* Compile data

* Extract data

* Manipulate data

* Prepare data for visualization and reporting



## Course Philosophy

Analysis of data helps us make better decisions. And computers have accelerated how much data we can analyze.

The emphasis in this course will be on the data itself: where it comes from, how it is encoded, how it is stored, extracted, transformed, and loaded into tools that facilitate modeling, visualization, and communication. 

In this course we will be primarily using the open source programming language R, with tangents into SQL and Python.



***

## Course Outline

**_subject to change_**

| Week      | Date | Topics   | Lesson |
|---        |:---  |:---      |:---:  |
|1a          | 2020-09-05 | Introduction <br> | &#8212; |
|1b          | 2020-09-06 | Data collection | &#8212; |
|2a          | 2020-09-12 | Importing data: different formats | &#8212; |
|2b          | 2020-09-13 | Web scraping | &#8212; |
|3a          | 2020-09-19 | Transform: Cleaning data | &#8212; |
|3b          | 2020-09-20 | Transform: Data validation | &#8212; |
|4a          | 2020-09-26 | Data storage | &#8212; |
|4b          | 2020-09-27 | Data transformation: structure | &#8212; |
|5a          | 2020-10-03 | Data transformation: manipulation | &#8212; |
|5b          | 2020-10-04 | Data documentation | &#8212; |
|6a          | 2020-09-10 | Preparing for reporting | &#8212; |
|6b          | 2020-09-11 | Maintaining privacy | &#8212; |




#### Concordance: course objective to lesson topics

| Course objective      | Lesson topic   | Lessons |
|---        |:---  |:---:  |
| Import and export data | &#8212; | &#8212;  |
| Clean data | &#8212; | &#8212; | 
| Compile data | &#8212; | &#8212; | 
| Extract data | &#8212; | &#8212; |
| Manipulate data | &#8212; | &#8212; |
| Prepare data for visualization and reporting | &#8212; | &#8212; |
| Apply appropriate safeguards for data privacy and security | &#8212; | &#8212; |

***


## Evaluation



***


**_Bonus mark_**

Congratulations! You read to the end of the Syllabus. 

For a single bonus mark, before 2020-09-11 11:59 PM PDT please email me the following:

* a picture of a geographic location (a building, city skyline, natural landscape, etc., real or imaginary) with a bit of information as to what the picture shows, and why you chose it.



-30-
