---
title: "BIDA405: Lesson Plan, Week 3"
#subtitle: "2020-09-19 & 2020-09-20 "
author: "Martin Monkman"
date: "latest revision: `r Sys.Date()`"
output:
  word_document: default
  html_document: default
description: "Data Analytics Provisioning, Importing, Extracting and Manipulation, UVic BIDA405"
---




## Readings & Reference Materials



### Reading list

Randy Au, ["Data Cleaning IS Analysis, Not Grunt Work"](https://counting.substack.com/p/data-cleaning-is-analysis-not-grunt) (2020-09-15)

Karl Broman, "Tools for Reproducible Research: Organizing projects; exploratory data analysis":
https://kbroman.org/Tools4RR/assets/lectures/06_org_eda_withnotes.pdf

Jenny Bryan, "Naming Things", presentation to Reproducible Science Workshop: https://speakerdeck.com/jennybc/how-to-name-files

### Text references

Samuel E. Buttrey and Lyn R. Whitaker, _A Data Scientist's Guide to Acquiring, Cleaning and Managing Data in R_ (2017):

* Chapter 7, "Data Handling in Practice"

* [UVic library link](https://learning-oreilly-com.ezproxy.library.uvic.ca/library/view/a-data-scientists/9781119080022/c07.xhtml#c7)


Mark van der Loo and Edwin de Jonge, _Statistical Data Cleaning with Applications in R_ (2018):

* Chapter 6, "Data Validation" (sections 6.1-6.2)

* [UVic library link](https://learning-oreilly-com.ezproxy.library.uvic.ca/library/view/statistical-data-cleaning/9781118897157/c11.xhtml#c11)


Nina Zumel and John Mount, _Practical Data Science with R (2nd edition)_ (2020)

* Chapter 3 "Exploring Data" and Chapter 4 "Managing Data"

* [UVic library link](https://learning-oreilly-com.ezproxy.library.uvic.ca/library/view/practical-data-science/9781617295874/?ar?orpq&email=oJbr4Ho8VLXz0zbFzjLK2g%3d%3d&tstamp=1600527352&id=DC7689B4AD2FA446468DD1CE0CCCD91B187CD9C4)



### R help

Using the `?` and `??` approach to getting help with functions and packages:

* [Getting Help with R](https://www.r-project.org/help.html)

* [_R Cookbook_, 2nd edition: sections 1.7 to 1.14](https://rc2e.com/gettingstarted#recipe-id265)


### R examples

BC Stats - population estimates app 

* built in R using the {shiny} package: https://shiny.rstudio.com/

* the application: https://bcstats.shinyapps.io/popApp/

* github page for the code: https://github.com/bcgov/popApp



-30-
