---
title: "Import SPSS data"
output: html_notebook
---

<!-- 
This file by Martin Monkman is licensed under a Creative Commons Attribution 4.0 International License. 

The data file "PsychBike.sav" comes from the _Statistics for Psychology_ page at the University of Bath: https://people.bath.ac.uk/pssiw/stats2/page16/page16.html
-->


# Getting started

Run this code chunk:

```{r}
library(tidyverse)  
# we will be using the functions from {haven}
library(haven)

library(here)
```



# 1. Reading a SAV file

SAV files are SPSS data files. They save both the values and the labels for those values.

The package {haven} is designed to make importing these files simple.



Run this chunk to create an object called `mtcars`, from a CSV file of the same name.

```{r}
# example
psychbike <- haven::read_sav(here("data", "PsychBike.sav"))
#psychbike <- foreign::read.spss(here("data", "PsychBike.sav"))

head(psychbike)


```


Description of SPSS file: https://www.loc.gov/preservation/digital/formats/fdd/fdd000469.shtml


