---
title: "BIDA405 hexsticker"
output:
  html_document:
    df_print: paged
---


```{r setup}

library(hexSticker)

```

https://github.com/GuangchuangYu/hexSticker 

UVic logo
https://www.uvic.ca/brand/look-feel/logo/index.php 


UVic colour
https://www.uvic.ca/brand/look-feel/colour/palette/index.php


## fonts & colours

```{r fonts}

library(showtext)
## Loading Google fonts (http://www.google.com/fonts)
font_add_google("Poiret One", "poiret")
font_add_google("Raleway", "raleway")
font_add_google("Roboto Slab", "roboto_slab")

## loading local font 
font_add(family = "broadway", regular = "BROADW.TTF")

font_add("trebuchet",
         regular="C:\\Windows\\Fonts\\trebuc.ttf")

font_add("gill",
         regular="C:\\Windows\\Fonts\\GILSANUB.TTF")



## Automatically use showtext to render text for future devices
showtext_auto()


```


### colours


```{r colours}

uvic_blue <- "#005493"    #RGB: 0-84-147
uvic_yellow <- "#F5AA1C"    #RGB: 245-170-28  
uvic_red <- "#C63527"    #RGB: 198-53-39
uvic_blue_dark <- "#002754"  #RGB: 0-39-84

```



## organize

Icon: organize by Luis Herrera from the Noun Project
https://thenounproject.com/term/organize/1211773/ 


shaded circles on UVic yellow
https://maketintsandshades.com/#F5AA1C

Dark to light:

* #936611 - one row

* #c48816 - one row

* #f5aa1c - two rows

* #f7bb49 - one row

* #f9cc77 - one row

```{r}

i <- "noun_organize_1211773_3600_shaded.png"
BIDA405_hex2 <- 
  sticker(i, package="BIDA405", 
          s_x=1, s_y=.7, 
          s_width=.7, s_height=.7,
        h_fill=uvic_blue_dark, h_color=uvic_yellow, h_size = 1.5,
        p_color = uvic_yellow,
        p_size=24, 
#        p_x = 1, 
#        p_y = 1.4,
        p_family = "roboto_slab")

BIDA405_hex2

ggplot2::ggsave("BIDA405_hex.png", width = 2, height = 2)

#ggplot2::ggsave("BIDA405_hex.eps", width = 2, height = 2, device = "eps")

```


