---
title: 'Validation and cleaning'
output:
  html_document:
    df_print: paged
---

<!-- 
This file by Martin Monkman is licensed under a Creative Commons Attribution 4.0 International License. 
-->


# Getting started

We've read in our raw data. The next step is to make sure that the data is what we expect, and what we need for our analysis. We need to _clean the data_. Which doesn't sound like a lot of fun. Didn't we want to be data scientists or business intelligence experts or academic scientists to uncover the insights hiding in the data? 

> The act of cleaning data imposes values/judgments/interpretations upon data intended to allow downstream analysis algorithms to function and give results. That’s exactly the same as doing data analysis. In fact, “cleaning” is just a spectrum of reusable data transformations on the path towards doing a full data analysis. —Randy Au, 2020-09-15 ^[["Data Cleaning IS Analysis, Not Grunt Work"](https://counting.substack.com/p/data-cleaning-is-analysis-not-grunt)]


So what are we doing when we say we are "cleaning the data"? And how can we confirm that it is "cleaned" in the way that we have defined?

## Some things that go wrong

Underlying the belief that the data is "dirty" and needs cleaning is the assumption that something has gone wrong. So...what can go wrong?


What are common dirty data problems?

* Column headers are values instead of variable names, or there are duplicate variable names.

* Multiple data types in a column. For example, some records are numbers and some are character strings—and this could be entirely correct, but if some number entry includes commas as thousands separators, it might be stored as a character.

* Multiple variables are stored in one column (examples include first name & last name, city & province or state).

* Misspellings (typing errors) ^[In this tweet, you can see 57 different ways of spelling "Philadelphia" in the data collected in a US Government loan form(https://twitter.com/dataeditor/status/1280278987797942272?s=20)]

* Value in wrong field (e.g. country entered into `city` field).

* Irregularities in unit of measurement (in an international survey or form, `salary` completed by respondents in the values of their local currency).

* Default values in the place of missing values.

> Dr Davis Lawrence, director of safety-literature database the SafeLit Foundation...tells me that 'in most US states the quality of police crash reports is at best poor for use as a research tool. ... Data-quality checks were rare and when quality was evaluated it was found wanting. For example, in Louisiana for most crashes in the 1980s most of the occupants were males who were born on January 1st, 1950. Almost all of the vehicles involved in crashes were the 1960 model year.' Except they weren't. These were just the default settings. [@Criado_Perez_2019, p.190]

* Contradiction (for example, two databases with the same person but the date of birth differs, perhaps due to non-ISO8601 entry: 07-08-79 and 08-07-79 both have the same digits but one could be mm-dd-yy and the other dd-mm-yy...we just don't know which is the correct one. Or is one a typo?)


See [@Zumel_Mount_2019, chapters 3 and 4]





## REFERENCE MATERIAL

You can find more details in _R for Data Science_:
https://r4ds.had.co.nz/data-import.html


{readr} 
https://readr.tidyverse.org/

{readxl}
https://readxl.tidyverse.org/index.html


