---
title: "BIDA405: Lesson Plan, Week 2"
#subtitle: "2020-09-12 & 2020-09-13 "
author: "Martin Monkman"
date: "latest revision: `r Sys.Date()`"
output:
  word_document: default
  html_document: default
description: "Data Analytics Provisioning, Importing, Extracting and Manipulation, UVic BIDA405"
---




## Readings & Reference Materials



## Reading list

Paul Murrell, _Introduction to Data Technologies_:

* Chapter 5, "Data Storage"

  - [online version](https://www.stat.auckland.ac.nz/~paul/ItDT/HTML/node36.html)


* [entire book: homepage](https://www.stat.auckland.ac.nz/~paul/ItDT/)

* [UVic library link](https://learning-oreilly-com.ezproxy.library.uvic.ca/library/view/introduction-to-data/9781420065183/?ar?orpq&email=oJbr4Ho8VLXz0zbFzjLK2g%3d%3d&tstamp=1595819339&id=081854077E8F5A7C7006AE8AEE9FEC6EE37CC34A)


Samuel E. Buttrey and Lyn R. Whitaker, _A Data Scientist's Guide to Acquiring, Cleaning and Managing Data in R_ (2017):

* Chapter 6, "Getting Data into and out of R"

* [UVic library link](https://learning-oreilly-com.ezproxy.library.uvic.ca/library/view/a-data-scientists/9781119080022/c06.xhtml#c6)



Paul Murrell. 2013. “Data Intended for Human Consumption, Not Machine Consumption.” In _Bad Data Handbook_, edited by Q. Ethan McCallum, 31–51. O’Reilly.

* [UVic library link](https://learning-oreilly-com.ezproxy.library.uvic.ca/library/view/bad-data-handbook/9781449324957/ch03.html)



Tim Costello & Lori Blackshear, 2020, _Prepare Your Data for Tableau: A Practical Guide to the Tableau Data Prep Tool_, Apress/Springer.

* [UVic library link](https://link-springer-com.ezproxy.library.uvic.ca/content/pdf/10.1007%2F978-1-4842-5497-4.pdf)


April Reeve, 2013, _Managing Data in Motion : Data Integration Best Practice Techniques and Technologies_, Elsevier Science & Technology

* [UVic library link](https://ebookcentral-proquest-com.ezproxy.library.uvic.ca/lib/uvic/detail.action?docID=1152636)



### Regular expressions

[Chapter 10, Regular expressions in _Supervised Machine Learning for Text Analysis in R_](https://smltar.com/regexp.html) by Emil Hvitfeldt and Julia Silge, 2020


[regex101](https://regex101.com/)


### Web APIs

TBD --


### Webscraping

TBD --

Mine Dogucu and Mine Çetinkaya-Rundel, ["Web Scraping in the Statistics and Data Science Curriculum: Challenges and Opportunities"](https://doi.org/10.1080/10691898.2020.1787116), _Journal of Statistics Education_


### R packages

{polite}

* [package page](https://dmi3kno.github.io/polite/index.html)


{rvest}

* [package page](https://rvest.tidyverse.org/)

* ["rvest: easy web scraping with R"](https://blog.rstudio.com/2014/11/24/rvest-easy-web-scraping-with-r/) by Hadley Wickham (2014-11-24)

-30-
