---
title: "BIDA405: Lesson Plan, Week 2"
#subtitle: "2020-09-12 & 2020-09-13 "
author: "Martin Monkman"
date: "latest revision: `r Sys.Date()`"
output:
  word_document: default
  html_document: default
description: "Data Analytics Provisioning, Importing, Extracting and Manipulation, UVic BIDA405"
---

# Unit learning plan

## Saturday


### 1a. Homework review

Format: instructor lecture w/ slides

Time allocation: 15 minutes (9:00 to 9:15)


Format: breakout rooms

Time allocation: 15 minutes (9:15 to 9:30)



### 1b. Importing other data formats

_Import SPSS files_


Format: instructor, lecture w/slides

Time allocation: 15 minutes (9:30 to 9:45)



Format: hands-on exercise, learner (instructor guided)

Time allocation: 60 minutes (9:45 to 10:30)

Activity:

* import various files


***

## BREAK

Time allocation: 15 minutes (10:30 to 10:45)

***


### 2a. Import from web sources


Format: hands-on exercise

Time allocation: 45 minutes (10:45 to 11:30)


  - Statistics Canada {cansim}: https://mountainmath.github.io/cansim/index.html 
  
  - BC Data Catalogue {bcdata}: https://bcgov.github.io/bcdata/

  

### 2b. Excercise - Readings: project-oriented workflow

Format: instructor, lecture w/slides

Time allocation: 15 minutes (11:45 to 11:00)


Last week, the reading focussed on the end result of the import:tidy:transform process—the data artifacts and documentation that is produced. For this week's between-class-readings, we will look at two related articles that stress the importance of _how_ we work. In particular, the focus is on creating a self-contained **project**, both the how and the why. (These are about projects using R and RStudio, but the principles apply no matter what tool you use.)

Please read:

* Hadley Wickham and Garrett Grolemund, [_R for Data Science_, Chapter 8—Workflow: projects](https://r4ds.had.co.nz/workflow-projects.html)

* Jenny Bryan, [Project-oriented workflow](https://www.tidyverse.org/blog/2017/12/workflow-vs-script/)

  - Optional: [a subsequent discussion on RStudio Community](https://community.rstudio.com/t/project-oriented-workflow-setwd-rm-list-ls-and-computer-fires/3549) will provide some additional ideas about Project-oriented workflow.

Note that  `rm()` removes specified objects, and `ls()` creates a list of all of the objects in your environment. So combining them into `rm(list = ls())` clears all of the objects out of your environment.


Come to class on Sunday ready to answer and discuss the following:

* What are some specific reasons why a project-based workflow will "maximize effectiveness and reduce frustration" (to quote Jenny Bryan)?

* What are the elements of your work that are "product" or "real"?  

Now, using the instructions in _R for Data Science_ ([8.4, RStudio projects](https://r4ds.had.co.nz/workflow-projects.html#rstudio-projects)), turn the folder with your BIDA405 materials into an RStudio "Project". Now you can simply click on the project, and it will launch RStudio with that folder as the "root". 

***

## Sunday


### 3a. Introductions

_who are we?_

Time allocation: 30 minutes (9:00 to 9:30)



### 3b. Discussion - Readings: project-oriented workflow


Format: breakout rooms

Time allocation: 15 minutes (9:30 to 9:45)


Format: lecture w/slides

Time allocation: 15 minutes (9:45 to 10:00)


### 3c. Webscraping - introduction

_Demonstrate basic understanding of regular expressions and their utility_

Format: instructor lecture w/ slides

Time allocation: 30 minutes (10:00 to 10:30)



***

## BREAK

Time allocation: 15 minutes (10:30 to 10:45)


***

### 4a. Webscraping 

_Demonstrate basic understanding of approaches to webscraping_

Format: instructor lecture w/ slides

Time allocation: 15 minutes (10:45 to 11:30)


Format: hands-on exercise

Time allocation: 15 minutes (10:45 to 11:30)



Format: learner (instructor guided)

Time allocation: 30 minutes (11:30 to 11:45)


## 4b. Wrap up

Time allocation: 15 minutes (11:45 to 12:00)


### Summary

Format: instructor summary, w/ slides

### Preview/readings for next lesson

Format: instructor summary, w/ slides

### Questions?

Format: learner Q&A




***

