---
title: "BIDA405: Lesson Plan, Week 2"
#subtitle: "2020-09-12 & 2020-09-13 "
author: "Martin Monkman"
date: "latest revision: `r Sys.Date()`"
output:
  word_document: default
  html_document: default
description: "Data Analytics Provisioning, Importing, Extracting and Manipulation, UVic BIDA405"
---


***

**_subject to change_**



## Objectives


At the end of the first part of this lesson, learners will:

1. Demonstrate the ability to load data from a variety of file and web sources into an R environment; and 



At the end of the second part of this lesson, learners will:

1. Understand the underlying structure of a webpage; and  

1. Webscraping: demonstrate how to read data stored in a webpage into an R environment.


***

## Activities: summary

| Block      | Time           | Topics  | &#8212; |
|---         |:---            |:---     |:---:  |
|**Saturday**|**Data from other documents**     |&#8212; |&#8212; |
|1a          | 9:00 to 9:30   | Homework review  | &#8212; |
|1b          | 9:30 to 10:30  | Importing other data formats: SPSS | &#8212; |
|&#8212:     | 10:30 to 10:45 | _break_ | &#8212; |
|2a          | 10:45 to 11:30 | Importing from web sources | &#8212; |
|2b          | 11:30 to 12:00 | Homework <br> - Readings: project-based workflow | &#8212; |
|**Sunday**  |**Web scraping** |&#8212; |&#8212; |
|3a          | 9:00 to 9:30   | Discussion <br> - Readings: project-based workflow  | &#8212; |
|3b          | 9:30 to 10:30  | Webscraping - introduction | &#8212; |
|&#8212:     | 10:30 to 10:45 | _break_ | &#8212; |
|4a          | 10:45 to 11:45 | Webscraping - part 2 | 
|4b          | 11:45 to 12:00 | Homework assignment <br> Wrap-up and summary | &#8212; |


***

