---
title: "Preparing files"
subtitle: ""
output:
  html_document:
    df_print: paged
---

<!-- 
This file by Martin Monkman is licensed under a Creative Commons Attribution 4.0 International License. 
-->

```{r setup, message=FALSE, warning=FALSE}
# data wrangling
library(tidyverse)

```

## Objectives

* Demonstrate understanding of 



## Preparing files

At the end of the import > cleaning > manipulation > save stream comes the step of ensuring that the files are ready to be sent on to the next step in the process, whether that's modeling, visualization, or publication.

If there are no privacy or confidentiality concerns, you might simply hand your cleaned file with all of the records to whoever is responsible for the next step.

But very often, there _are_ privacy or confidentiality risks associated with sharing the file. Data about penguins or the results of professional sports don't carry the requirement for confidentiality, but data collected about people does. This data might be financial, health-related, or political opinion. In Canada, there are many laws that provide protections of our personal information that is collected by government agencies and private businesses. 

https://blog.servermania.com/canadian-vs-american-data-privacy-laws-how-do-they-compare/




***

## REFERENCE

### Packages

{readr}: https://readr.tidyverse.org/index.html

{readxls}: 

