---
title: "Confidentiality"
subtitle: "Statistical Disclosure Control"
author: "Martin Monkman"
date: "2020/10/10"
output:
  xaringan::moon_reader:
    css: [default, css_files/eigengrau.css, css_files/eigengrau-fonts.css]    
    lib_dir: libs
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---


```{r setup, include=FALSE}
options(htmltools.dir.version = FALSE)
```


class: inverse

# Our journey so far...

* Importing data
* Cleaning data
* Data manipulation
* Data structures
* SQL
* Saving our data files
* Recordkeeping & documentation


---
class: inverse


## Next: 

## Publishing your data


---
class: inverse

## Why?

* transfer to visualization or download tool

* publish ("open data")

* as part of analytic report



---
class: inverse

## Privacy

When working with data, we need to be able to uniquely identify individuals or businesses

* business: inventory and orders

* administrative: customer or client database

* survey: link to administrative records

* modeling: link across admin databases


--

_BUT_...when sharing data, we need to adopt proper privacy protocols

???

Hart, Barmby, et al. "Ten Simple Rules for Digital Data Storage"

---
class: inverse

## Confidentiality of data

Some data is more sensitive

* business data

  - number of employees vs profit margin

* personal information

  - number of bicycles vs health issues



---
class: inverse

## Laws

### British Columbia

* Personal Information Protection Act

* Freedom of Information and Protection of Privacy Act

Office of the Information & Privacy Commissioner

* [oipc.bc.ca](https://www.oipc.bc.ca/about/legislation/) 

---
class: inverse

## Laws

### Canada

* The Personal Information Protection and Electronic Documents Act

* Privacy Act

Office of the Privacy Commissioner of Canada

* [priv.gc.ca](https://www.priv.gc.ca/en/privacy-topics/privacy-laws-in-canada/02_05_d_15)


---
class: inverse

## So what can be released?


Intention: provide as much data as possible, without revealing individually identifiable data



???

Source: _Report on Statistical Disclosure Limitation Methodology_ SPWP22 (2005), Office of Management and Budget

---
class: inverse

## Types of variables

1. Non-confidential variables

2. Direct identifiers

3. Indirect identifers

  - implicit or quasi-identifiers

???

Matthias Templ, _Statistical Disclosure Control for Microdata: Methods and Applications in R_, 2017




---
class: inverse

## Risk: by types of disclosure

* identity disclosure

* attribute disclosure

* inferential disclosure

???

Matthias Templ, _Statistical Disclosure Control for Microdata: Methods and Applications in R_, 2017


---
class: inverse

## Concept: residual disclosure

Suppression in one row or column will require suppression in another

---

## Residual disclosure: counts

Here's a table with three people, and how many apples they have. In this place, there is disclosure of 5 or more apples, but fewer than that gets suppressed.

| name | apples_n |
|---|---|
| Holly | 5 |
| Ivy | 15 |
| Lily | 1 |
| TOTAL | 21 |

---

| name | apples_n |
|---|---|
| Holly | 5 |
| Ivy | 15 |
| Lily | - |
| TOTAL | 21 |

If we are concerned about the low number that Lily has and suppress it, we haven't hidden anything—it's still possible to calculate it as the _residual_ of the other values.

---

## Solution

| name | apples_n |
|---|---|
| Holly | - |
| Ivy | 15 |
| Lily | - |
| TOTAL | 21 |

If we suppress Lily's apples, we also have to suppress Holly's—the difference of 6 (21-15) has multiple solutions, so it's impossible to know the precise number Holly and Lily have.


---

## Residual disclosure: calculated values

| name | apples_n | weight_avg_g | 
|---|---|---|
| Holly | 5 | 7 |
| Ivy | 15 | 8.5 |
| Lily | 1 | 8 |
| TOTAL | 21 | 8.12 |

Suppose we know how many apples everyone has—the personal information is the weight of their individual apples. Holly and Ivy have multiple apples, so there's no way to know the weight of any one apple. Can't we just suppress Lily's value of 8?

---

## Calculated values (2)

| name | apples_n | weight_avg_g | total_weight_g
|---|---|---|---|
| Holly | 5 | 7 | 35 |
| Ivy | 15 | 8.5 | 127.5 |
| Lily | 1 | X1 | X2 |
| TOTAL | 21 | 8.12 | Y |

We can solve for X

`X1 = X2`

`Y = (35 + 127.5 + X2)`

`Y = 21 * 8.12 = 170.52`

`X2 = 170.52 - (35 + 127.5) = 8.02`


---

## Residual disclosure: additional dimensions

Add columns (additional dimensions)

What happens if we have an additional dimension--the type of fruit?

| name | apples_n | oranges_n | total_fruit_n
|---|---|---|---|
| Holly | 5 | 10 | 15 |
| Ivy | 15 | 10 | 25 |
| Lily | 1 | 5 | 6 |
| TOTAL | 21 | 25 | 46 |

---


We still need to suppresss Lily's one apple


| name | apples_n | oranges_n | total_fruit_n
|---|---|---|---|
| Holly | 5 | 10 | 15 |
| Ivy | 15 | 10 | 25 |
| Lily | - | 5 | 6 |
| TOTAL | 21 | 25 | 46 |

But now we also have a residual on the row, as well as the column.

---


| name | apples_n | oranges_n | total_fruit_n
|---|---|---|---|
| Holly | - | - | 15 |
| Ivy | 15 | 10 | 25 |
| Lily | - | - | 6 |
| TOTAL | 21 | 25 | 46 |

And suppressing the numbers of Lily's apples & oranges still leaves the residual, so we also have to suppress Holly's apples and oranges.


---
class: inverse

## Hierarchical structure of variables

* geography

  - Country > Province > Regional District > Municipality
  
* NAICS

  - Sector > Industry Group > Industry 



---
class: inverse

# Hierarchical suppression

Start with the largest unit, and suppress the lower levels of the hierarchy

* _suppress sub-categories before categories_

* suppress apples and oranges before total fruit

* suppress city before province, province before country

---
class: inverse

## Suppression

You may (will?!) face choices 

* penguins: would you suppress species, island, or sex?

_The answer depends on the research question_


---
class: inverse

## Other ways to prevent disclosure

* rounding (nearest 10, 100, 1000, ...)

* random rounding, other manipulation

* grouping cases ("binning")

  - 5-year age group instead of single age

* suppression (printing "NA")


---
class: inverse

So...what are the rules to follow?

--

**_It depends_**

---
class: inverse

## One example of rules

**BC Government's Secure Research Enviroment (SRE)**

**_Output Guidance for Users_** 

---
class: inverse

## Overall Rules of Thumb

* 10 units in all tabular output underlying any data point

* 10 degrees of freedom in any modeled output

* Group disclosure: in all tabular output, no cell can contain more than 90% of the total of the row or column

* Dominance: the largest contributor to a cell should not contribute more than 50% of the total in the cell

---
class: inverse

-30-
